name: myWorkflow
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.capture_tag.outputs.tag_version }}
    steps:
    - id: step1
      uses: actions/checkout@main
      with:
        fetch-depth: '0'
    - name: Push tag
      id: push_tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
    - id: capture_tag
      run: |
        echo '::echo::on'
        echo "::set-output name=tag_version::${{ steps.github-tag-action.outputs.new_tag }}"
  build:
    needs: checkout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: ['3.5.4']
        java: ['11']
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Build with Maven
        run: mvn verify
  publish:
    needs: build
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        #title: ${{ needs.checkout.outputs.output1 }}
        title: MyGitHubRelease
  finalization:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: '0'
    - name: Push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true